# Generated by Django 5.1 on 2024-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('moblie', 'moblie'), ('electrnoics', 'electrnoics'), ('fashion', 'fashion'), ('babyproduct', 'babyproduct')], max_length=100),
        ),
    ]
