# Generated by Django 5.1 on 2024-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('babyproduct', 'Baby Product')], max_length=100),
        ),
    ]
